CubeToolsPublicSite/CubeToolsPublicSite/Controllers/AboutController.cs
using _4Log.Log;
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CubeToolsPublicSite.Controllers
{
	public class AboutController : BaseController
	{
		// GET: About
		public ActionResult Index()
		{
			return View();
		}
		public ActionResult Company()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Company", ex);
				return View();
			}

		}
		public ActionResult OurTeam()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in OurTeam", ex);
				return View();
			}

		}
		public ActionResult Expertise()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Expertise", ex);
				return View();
			}

		}

		public ActionResult Security()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Security", ex);
				return View();
			}

		}
		public ActionResult Technology()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Technology", ex);
				return View();
			}

		}
		public ActionResult Portfolio()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Portfolio", ex);
				return View();
			}

		}
		public ActionResult Careers()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Careers", ex);
				return View();
			}

		}

		public ActionResult CustomerSupport()
		{
			try
			{
				return View();
			}

			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Careers", ex);
				return View();
			}

		}
		
		public ActionResult Clients()
		{
			try
			{
				return View();
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Clients view", ex);
				return View();
			}
		}
	}
}

CubeToolsPublicSite/CubeToolsPublicSite/Views/Shared/_Comments.cshtml
<section class="comments gray-section" style="margin-top: 0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>What our partners say</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada. </p>
            </div>
        </div>
        <div class="row features-block">
            <div class="col-lg-4">
                <div class="bubble">
                    "Uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
                </div>
                <div class="comments-avatar">
                    <a href="" class="pull-left">
                        <img alt="image" src="~/Images/landing/avatar3.jpg">
                    </a>
                    <div class="media-body">
                        <div class="commens-name">
                            Andrew Williams
                        </div>
                        <small class="text-muted">Company X from California</small>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="bubble">
                    "Uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
                </div>
                <div class="comments-avatar">
                    <a href="" class="pull-left">
                        <img alt="image" src="~/Images/landing/avatar1.jpg">
                    </a>
                    <div class="media-body">
                        <div class="commens-name">
                            Andrew Williams
                        </div>
                        <small class="text-muted">Company X from California</small>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="bubble">
                    "Uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
                </div>
                <div class="comments-avatar">
                    <a href="" class="pull-left">
                        <img alt="image" src="~/Images/landing/avatar2.jpg">
                    </a>
                    <div class="media-body">
                        <div class="commens-name">
                            Andrew Williams
                        </div>
                        <small class="text-muted">Company X from California</small>
                    </div>
                </div>
            </div>



        </div>
    </div>

</section>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Shared/_ErrorLayout.cshtml
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
   
    <link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <link href="~/Content/style.css" rel="stylesheet" />

</head>

<body class="gray-bg">
    @RenderBody()

    <script src="~/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>

</html>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Shared/_ErrorPartial.cshtml
<script type="text/javascript">
	 $(document).ready(function () {
	 	 var errorspan = '';
	 	 var text = $('@Html.ValidationMessage("error")').text();

	 	 if (text != null && text.toString().trim()!='') {
	 	 	 new Notification(text, "@SharedResources.Resources.ErrorMessageTitle", 'error');
	 	 }
	 });
</script>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Shared/_Features.cshtml
<section id="features" class="container services wow fadeInUp animated">
    @if (ViewBag.Type == "Home")
	 {
    <h2 class="slogan">@Html.Raw(Resources.HomeSloganText)<br></h2>
	 <div class="box-column2">
			<div class="row">
				<div class="col-sm-4">
					 <div class="div-cube">
						  <div class="detail-box">
								<div class="detail-entry">
									 <a href="@Url.Action("Index", "CubeSoftware")">
										  <img class="div-cube-img" src="~/Images/CubeImages/Cubo blu.png" />
										  <h2>@Resources.CubeSoftware</h2>
									 </a>
									 <p>@Resources.CubeSoftwareDesc</p>
								</div>
						  </div>
					 </div>
				</div>
				<div class="col-sm-4">
					 <div class="div-cube">
						  <div class="detail-box">
								<div class="detail-entry">
									 <a href="@Url.Action("Index","CubeServices")">
										  <img class="div-cube-img" src="~/Images/CubeImages/Cubo-verde_piccolo.png" />
										  <h2>@Resources.CubeServices</h2>
									 </a>
									 <p>@Resources.CubeServicesDesc</p>
								</div>
						  </div>
					 </div>
				</div>
				<div class="col-sm-4">
					 <div class="div-cube">
						  <div class="detail-box">
								<div class="detail-entry">
									 <a href="@Url.Action("Index","Consulting")">
										  <img class="div-cube-img" src="~/Images/CubeImages/Cubo arancio.png" />
										  <h2>@Resources.Consulting</h2>
									 </a>
									 <p>@Resources.ConsultingDesc</p>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	</div>
	 }
    @if (ViewBag.Type == "CubeSoftware")
	 {
    <h2 class="slogan">@Html.Raw(Resources.CubeSoftwareSloganText)<br></h2>
    <div class="box-column3">
        <div class="row">
            <div class="col-sm-3">
                @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@

                <div class="detail-box detail-cube">
                    <div class="detail-entry">
                        <a href="@Url.Content("~/CubeSoftware/CubeRiskManagementOverview")"><h2>@Resources.CubeRiskManagement</h2></a>
                        <p>@Resources.CubeRiskDesc</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@
                <div class="detail-box detail-cube">
                    <div class="detail-entry">
                        <a href="@Url.Content("~/CubeSoftware/PortfolioCubeOverview")">
                            <h2>@Resources.PortfolioCube</h2>
                        </a>
                        <p>@Resources.PortfolioCubeDesc</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@

                <div class="detail-box detail-cube">
                    <div class="detail-entry">
                        <a href="@Url.Content("~/CubeSoftware/CubePreTradeOverview")">
                            <h2>@Resources.CubePreTrade</h2>
                        </a>
                        <p>@Resources.CubePreTradeDesc</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@

                <div class="detail-box detail-cube">
                    <div class="detail-entry">
                        <a href="@Url.Content("~/CubeSoftware/OptionCubeOverview")">
                            <h2>@Resources.OptionCube</h2>
                        </a>
                        <p>@Resources.OptionCubeDesc</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
	 }
    @if (ViewBag.Type == "CubeServices")
	 {
    <div class="row">
        <h2 class="slogan">@Html.Raw(Resources.CubeServicesSloganText)<br></h2>
        <div class="col-sm-3">
            @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@

            <div class="detail-box detail-cube">
                <div class="detail-entry">
                    <a href="@Url.Content("~/CubeServices/CubeVolatilityOverview")"><h2>@Resources.CubeVolatility</h2></a>
                    <p>@Resources.CubeVolatilityDesc</p>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@

            <div class="detail-box detail-cube">
                <div class="detail-entry">
                    <a href="@Url.Content("~/CubeServices/CubeMarginsOverview")">
                        <h2>@Resources.CubeHMargins</h2>
                    </a>
                    <p>@Resources.CubeHMarginsDesc</p>
                </div>
            </div>

        </div>

        <div class="col-sm-3">
            @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@

            <div class="detail-box detail-cube">
                <div class="detail-entry">
                    <a href="@Url.Content("~/CubeServices/CubeGreeksOverview")">
                        <h2>@Resources.CubeHGreeks</h2>
                    </a>
                    <p>@Resources.CubeHGreeksDesc</p>
                </div>
            </div>

        </div>
        <div class="col-sm-3">
            @*<div class="div-cube"><img src="~/Images/landing/grid.png" /></div>*@           
            <div class="detail-box detail-cube">
                <div class="detail-entry">
                    <a href="@Url.Content("~/CubeServices/CubeAPIMarginsOverview")">
                        <h2>@Resources.CubeAPIMargins</h2>
                    </a>
                    <p>@Resources.CubeAPIMarginsDesc</p>
                </div>
            </div>
        </div>
    </div>
	 }
    @if (ViewBag.Type == "Consulting")
	 {
    <h2 class="slogan">@Html.Raw(Resources.ConsultingSloganText)<br></h2>
	 <div class="box-column2">
		  <div class="row">
				<div class="col-sm-4">
					 <div class="detail-box detail-cube">
						  <div class="detail-entry">
								<a href="@Url.Content("~/Consulting/RiskManagementOutsourcing")">
									 <h2>@Resources.RiskManagementOutsourcing</h2>
								</a>
								<p>@Resources.ManagementOutsourcingDesc</p>
						  </div>
					 </div>
				</div>
				<div class="col-sm-4">
					 <div class="detail-box detail-cube">
						  <div class="detail-entry">
								<a href="@Url.Content("~/Consulting/RiskManagementConsulting")">
									 <h2>@Resources.RiskManagementConsulting</h2>
								</a>
								<p>@Resources.ManagementConsultingDesc</p>

						  </div>
					 </div>
				</div>
				<div class="col-sm-4">
					 <div class="detail-box detail-cube">
						  <div class="detail-entry">
								<a href="@Url.Content("~/Consulting/InvestmentAdvisory")">
									 <h2>@Resources.InvestmentAdvisory</h2>
								</a>
								<p>@Resources.InvestmentAdvisoryDesc</p>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 }
    @if (ViewBag.Type == "Download")
	 {
    <div class="row">
        <div class="col-sm-4">
            <a href="#"><h2>@Resources.WhitePaper</h2></a>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
            <p><a class="navy-link" data-toggle="modal" href="#modal-form" role="button">Details &raquo;</a></p>
        </div>
        <div class="col-sm-4">
            <a href="javascript:void(0)">
                <h2>@Resources.CaseStudies</h2>
            </a>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
            <p><a class="navy-link" data-toggle="modal" href="#modal-form" role="button">Details &raquo;</a></p>
        </div>
        <div class="col-sm-4">
            <a href="javascript:void(0)">
                <h2>@Resources.Howto</h2>
            </a>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
            <p><a class="navy-link" data-toggle="modal" href="#modal-form" role="button">Details &raquo;</a></p>
        </div>
    </div>
	 }
</section>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Shared/_LandingPartial.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-16x16.png">

    <title>Cube Finance</title>
   
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    @*<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>*@
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->

    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/css")

</head>
<body id="page-top" class="landing-page">
   
    @Scripts.Render("~/bundles/jquery")
    @*<script src="~/Scripts/jquery.themepunch.plugins.min.js"></script>*@
    @*<script src="~/Scripts/jquery-1.11.3.js"></script>*@

    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    @Scripts.Render("~/Scripts/Themepunch")

    @Html.Partial("_TopNavbar")

    @if (ViewBag.LagalPrivacy != true)
	 {

    @Html.Partial("_Slider")

    @Html.Partial("_Features")

	 }

    <!-- Top Navbar -->
    @*@Html.Action("TopMenus", "Home")*@


    <!-- Main view  -->
    <div class="page-wrapper" id="pageHeader">
        @RenderBody()
    </div>

    <!-- Footer  -->
    @Html.Partial("_Footer")

 
   
    <!-- End page wrapper-->
    <!-- Section for main scripts render -->
    <script src="~/Scripts/jquery.maskedinput.js"></script>
</body>
</html>

<script src="~/Scripts/CommanJs/CommanJSFunctions.js"></script>
<script data-pace-options='{ "ajax": false }' src='~/Scripts/plugins/pace/pace.min.js'></script>
<script type="text/javascript">
	 $(document).ready(function () {

	 	 if ('@ViewBag.LagalPrivacy' == 'True') {
	 	 	 $("#pageHeader").addClass('privacy');
	 	 }
	 });
</script>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Shared/_Layout.cshtml
@using CubeToolsPublicSite.Helpers;
<!DOCTYPE html>
<html>
<head>
   
   
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-16x16.png">

    <title>Cube Finance  | @ViewBag.Title</title>


    @*<link href='http://fonts.googleapis.com/css?family=Calibri:400,300,600,700' rel='stylesheet' type='text/css'>*@
    @*<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Calibri" />*@
   
    <!-- Section for main scripts render -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    @Scripts.Render("~/plugins/toastr")
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->
    @Styles.Render("~/plugins/toastrStyles")
    
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/css")


    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</head>
<body >

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <!-- Navigation -->
   
        @Html.Partial("_Navigation")
	     
    <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">
        <!-- Page wraper -->
        <!-- Top Navbar -->
        @*@Html.Partial("_TopNavbar_1")*@
        @Html.Action("InnerTopMenus", "Home")
        <!-- Main view  -->
  
        @RenderBody()

        <!-- Footer -->
        @*@Html.Partial("_Footer")*@

        <!-- End page wrapper-->
        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>

    <!-- End wrapper-->
    <!-- Skin config script - only for demo purpose-->
    @*@Scripts.Render("~/bundles/custom")*@

    @Html.Partial("_ErrorPartial")
</body>
</html>
<script src="~/Scripts/CommanJs/CommanJSFunctions.js"></script>
<script data-pace-options='{ "ajax": false }' src='~/Scripts/plugins/pace/pace.min.js'></script>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Shared/_TopNavbar.cshtml
@*@model CubeToolsPublicSite.Models.Menus*@

<nav class="navbar navbar-default " id="navMenu" role="navigation">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse" >        
            <a href="@Url.Action("Index","Home")" class="brand-logo stcky-hed"><img src="@Url.Content("~/Images/landing/cubepublic-logo.png")" alt="Cube Finance Logo" /></a>
            <ul class="nav navbar-nav" >
                <li id="Home" ><a href="@Url.Action("Index", "Home")">@Resources.Home</a></li>
                @*<li><a href="@Url.Action("Company", "About")">@Resources.AboutCubeFinance</a></li>*@
                <li id="About" class="root">

                    <a href="@Url.Action("Company", "About")">@Resources.AboutCubeFinance<b class="caret"></b></a>
                    <span class="dropdown-toggle hide-for-desktop" data-toggle="dropdown"><b class="caret"></b></span>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Content("~/About/Company")">@Resources.Company</a>
                        </li>
                        <li>
                            <a href="@Url.Content("~/About/OurTeam")">@Resources.OurTeam</a>
                        </li>
                        <li>
                            <a href="@Url.Content("~/About/Clients")">@Resources.LabelForClients</a>
                        </li>
                        <li>
                            <a href="@Url.Content("~/About/Portfolio")">@Resources.Portfolio</a>
                        </li>
                        <li>
                            <a href="@Url.Content("~/About/Careers")">@Resources.Careers</a>

                        </li>
                        <li>
                            <a href="@Url.Content("~/About/CustomerSupport")">@Resources.LabelForCustomerSupport</a>
                        </li>
                        <li>
                            <a href="@Url.Content("~/About/Security")">@Resources.Security</a>
                        </li>
                    </ul>
                </li>

                <li id="CubeSoftware" class="root">
                    <a href="@Url.Action("Index", "CubeSoftware")" >@Resources.CubeSoftware<b class="caret"></b></a>

                    <span class="dropdown-toggle hide-for-desktop" data-toggle="dropdown" ><b class="caret"></b></span>

                    <ul class="dropdown-menu  three-column column-menu">
                        <li>
                            <a class="headColumn" href="javascript:void(0)">@Resources.CubeRiskManagement</a>
                            <ul>
                                <li><a href="@Url.Content("~/CubeSoftware/CubeRiskManagementOverview")">@Resources.Overview</a></li>
                                <li><a href="@Url.Content("~/CubeSoftware/CubeRiskManagementFeatures")">@Resources.Features</a></li>
                                <li><a href="@Url.Content("~/CubeSoftware/Coverage")">@Resources.Coverage</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:void(0)" class="headColumn">@Resources.PortfolioCube</a>

                            <ul>
                                <li><a href="@Url.Content("~/CubeSoftware/PortfolioCubeOverview")">@Resources.Overview</a></li>
                                <li><a href="@Url.Content("~/CubeSoftware/PortfolioCubeFeatures")">@Resources.Features</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:void(0)" class="headColumn">@Resources.CubePreTrade</a>
                            <ul>
                                <li><a href="@Url.Content("~/CubeSoftware/CubePreTradeOverview")">@Resources.Overview</a></li>
                                <li><a href="@Url.Content("~/CubeSoftware/CubePreTradeFeatures")">@Resources.Features</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:void(0)" class="headColumn">@Resources.OptionCube</a>
                            <ul>
                                <li><a href="@Url.Content("~/CubeSoftware/OptionCubeOverview")">@Resources.Overview</a></li>
                                <li><a href="@Url.Content("~/CubeSoftware/OptionCubeFeatures")">@Resources.Features</a></li>
                            </ul>
                        </li>
                       
                    </ul>
                </li>

                <li id="CubeServices" class="root">

                    <a href="@Url.Action("Index", "CubeServices")">@Resources.CubeServices<b class="caret"></b></a>
                    <span class="dropdown-toggle hide-for-desktop" data-toggle="dropdown"><b class="caret"></b></span>
                    <ul class="dropdown-menu three-column column-menu">
                        <li>
                            <a class="headColumn" href="javascript:void(0)">@Resources.CubeVolatility</a>
                            <ul>
                                <li><a href="@Url.Action("CubeVolatilityOverview", "CubeServices")">@Resources.Overview</a></li>
                                <li><a href="@Url.Action("CubeVolatilityFeatures", "CubeServices")">@Resources.Features</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="headColumn" href="javascript:void(0)">@Resources.CubeHMargins</a>

                            <ul>
                                <li><a href="@Url.Action("CubeMarginsOverview", "CubeServices")">@Resources.Overview</a></li>
                                <li><a href="@Url.Action("CubeMarginsFeatures", "CubeServices")">@Resources.Features</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="headColumn" href="javascript:void(0)">@Resources.CubeHGreeks</a>
                            <ul>
                                <li><a href="@Url.Action("CubeGreeksOverview", "CubeServices")">@Resources.Overview</a></li>
                                <li><a href="@Url.Action("CubeGreeksFeatures", "CubeServices")">@Resources.Features</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="headColumn" href="javascript:void(0)">@Resources.CubeAPIMargins</a>
                            <ul>
                                <li><a href="@Url.Action("CubeAPIMarginsOverview", "CubeServices")">@Resources.Overview</a></li>
                                <li><a href="@Url.Action("CubeAPIMarginsFeatures", "CubeServices")">@Resources.Features</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>

                <li id="Consulting" class="root">

                    <a href="@Url.Action("Index", "Consulting")">@Resources.Consulting<b class="caret"></b></a>
                    <span class="dropdown-toggle hide-for-desktop" data-toggle="dropdown"><b class="caret"></b></span>
                    <ul class="dropdown-menu">
                        <li>
                            <a  href="@Url.Content("~/Consulting/RiskManagementOutsourcing")">@Resources.RiskManagementOutsourcing</a>
                        </li>
                        <li>
                            <a  href="@Url.Content("~/Consulting/RiskManagementConsulting")">@Resources.RiskManagementConsulting</a>

                        </li>
                        <li>
                            <a  href="@Url.Content("~/Consulting/InvestmentAdvisory")">@Resources.InvestmentAdvisory</a>
                        </li>
                    </ul>
                </li>
                <li id="Consulting" class="root">

                    <a href="@Url.Action("Index", "News")">@Resources.NewsLabel </a>
                    <span class="dropdown-toggle hide-for-desktop" data-toggle="dropdown"><b class="caret"></b></span>
                  
                </li>
                <li  class="root">
                    <a href="javascript:void(0)">@Resources.Language<b class="caret"></b></a>
                    <span class="dropdown-toggle hide-for-desktop" data-toggle="dropdown"><b class="caret"></b></span>
                    <ul class="dropdown-menu">
                        @*<li>
                            <a href="#">@Resources.VolatilityAnalysis</a>
                        </li>*@
                        <li><a href="@Url.Content("~/Home/SetCulture?culture=en-us")"><img src="~/Images/countryflag/gb.gif" /> English</a></li>
                        <li><a href="@Url.Content("~/Home/SetCulture?culture=it-CH")"><img src="~/Images/countryflag/it.gif" /> Italian</a></li>
                        <li><a href="@Url.Content("~/Home/SetCulture?culture=fr-FR")"><img src="~/Images/countryflag/fr.gif" /> French</a></li>
                    </ul>
                </li>
            </ul>            
            <div class="top-button stcky-hed">
                <a href="@Url.Action("ContactUs", "Home")"  class="btn btn-primary-topheader btn-lg"><strong>@Resources.LabelForDemo</strong>
                    @*<button type="button" id="btnDemo" class="btn btn-primary-topheader btn-lg"><strong>@Resources.LabelForDemo</strong></button>*@
                </a>                
                <a href="@Url.Content(System.Configuration.ConfigurationManager.AppSettings["PrivateLoginUrl"])" class="btn btn-primary-topheader btn-lg"><strong>@Resources.LabelForLogin</strong>
                    @*<button type="button" id="btnLogin" class="btn btn-primary-topheader btn-lg"><strong>@Resources.LabelForLogin</strong></button>*@
                </a>
            </div>
        </div>
    </div>
</nav>