CubeToolsPublicSite/CubeToolsPublicSite/Controllers/AnalysisController.cs
using System;
using System.Web.Mvc;
using log4net;
using _4Log.Log;
namespace CubeToolsPublicSite.Controllers
{
	public class AnalysisController : BaseController
	{
		public ActionResult VolatilityAnalysis()
		{
			try
			{
				return View();
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in Volatility Analysis", ex);
				return View();
			}

		}
		public ActionResult VaRAnalysis()
		{
			try
			{
				return View();
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in  VaR Analysis", ex);
				return View();
			}
			

		}
		public ActionResult SensitivityAnalysis()
		{
			try
			{
				return View();
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("error", ex.Message);
				LogObject.WriteErrorLogWithMessage("Error in  Sensitivity Analysis", ex);
				return View();
			}
			

		}
	}
}

CubeToolsPublicSite/CubeToolsPublicSite/Views/Analysis/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Analysis/SensitivityAnalysis.cshtml
@{
    ViewBag.Title = "SensitivityAnalysis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@Html.Raw(SharedResources.Resources.SensitivityAnalysis)</h2>
        <ol class="breadcrumb">

            <li>
                <a href="@Url.Action("Index", "Home" )">@Resources.Home</a>
            </li>
            <li>
                <a href="@Url.Action("VolatilityAnalysis", "Analysis")">@SharedResources.Resources.Analysis</a>

            </li>
            <li class="active">
                <strong>@Html.Raw(SharedResources.Resources.SensitivityAnalysis)</strong>
            </li>
        </ol>
    </div>

</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="form-horizontal">

        <div class="ibox-content">
            @Html.Raw(SharedResources.Resources.SensitivityAnalysisInfo)
        </div>

    </div>
</div>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Analysis/VaRAnalysis.cshtml
@{
    ViewBag.Title = "VaRAnalysis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@Html.Raw(SharedResources.Resources.VaRAnalysis)</h2>
        <ol class="breadcrumb">

            <li>
                <a href="@Url.Action("Index", "Home" )">@Resources.Home</a>
            </li>
            <li>
                <a href="@Url.Action("VolatilityAnalysis", "Analysis")">@SharedResources.Resources.Analysis</a>

            </li>
            <li class="active">
                <strong>@Html.Raw(SharedResources.Resources.VaRAnalysis)</strong>
            </li>
        </ol>
    </div>

</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="form-horizontal">

        <div class="ibox-content">
            @Html.Raw(SharedResources.Resources.VaRAnalysisInfo)
        </div>

    </div>
</div>

CubeToolsPublicSite/CubeToolsPublicSite/Views/Analysis/VolatilityAnalysis.cshtml
@{
    ViewBag.Title = "VolatilityAnalysis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@Html.Raw(Resources.VolatilityAnalysis)</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home" )">@Resources.Home</a>

            </li>
            <li>
                <a href="@Url.Action("VolatilityAnalysis", "Analysis")">@Resources.Analysis</a>

            </li>
            <li class="active">
                <strong>@Html.Raw(Resources.VolatilityAnalysis)</strong>
            </li>
        </ol>
    </div>

</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="form-horizontal">

        <div class="ibox-content">
            @Html.Raw(Resources.VolatilityAnalysisInfo)
        </div>

    </div>
</div>